init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: 0.10

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - ps: npm test
  - cmd: npm test
